// <auto-generated />
using System;
using FortunaPrimigenia.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FortunaPrimigenia.Api.Migrations
{
    [DbContext(typeof(FortunaPrimigeniaContext))]
    partial class FortunaPrimigeniaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("FortunaPrimigenia.Api.Models.Domain.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnBudget")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("FortunaPrimigenia.Api.Models.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryName = "Food",
                            CreatedDate = new DateTime(2026, 3, 3, 8, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 0,
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 3, 3, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            CategoryName = "Fuel",
                            CreatedDate = new DateTime(2026, 3, 3, 8, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 0,
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 3, 3, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            CategoryName = "Entertainment",
                            CreatedDate = new DateTime(2026, 3, 3, 8, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 0,
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 3, 3, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            CategoryName = "Groceries",
                            CreatedDate = new DateTime(2026, 3, 3, 8, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 0,
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 3, 3, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            CategoryName = "Health",
                            CreatedDate = new DateTime(2026, 3, 3, 8, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 0,
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 3, 3, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            CategoryName = "Education",
                            CreatedDate = new DateTime(2026, 3, 3, 8, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 0,
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 3, 3, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            CategoryName = "Household Goods",
                            CreatedDate = new DateTime(2026, 3, 3, 8, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 0,
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 3, 3, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            CategoryName = "Other",
                            CreatedDate = new DateTime(2026, 3, 3, 8, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 0,
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 3, 3, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 9,
                            CategoryName = "Income This Month",
                            CreatedDate = new DateTime(2026, 3, 3, 8, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 0,
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 3, 3, 8, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 10,
                            CategoryName = "Income Next Month",
                            CreatedDate = new DateTime(2026, 3, 3, 8, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 0,
                            IsActive = true,
                            ModifiedDate = new DateTime(2026, 3, 3, 8, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("FortunaPrimigenia.Api.Models.Domain.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("InflowAmount")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCleared")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Memo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("OutflowAmount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Payee")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("FortunaPrimigenia.Api.Models.Domain.Transaction", b =>
                {
                    b.HasOne("FortunaPrimigenia.Api.Models.Domain.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FortunaPrimigenia.Api.Models.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FortunaPrimigenia.Api.Models.Domain.Account", b =>
                {
                    b.Navigation("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
